name: Deploy Sphinx documentation to GitHub Pages

on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash -el {0}

jobs:
  build-with-sphinx:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    # permissions:
    #   pages: write
    #   id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Build | Make conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.13"
      - name: Build | Install dependencies
        run: |
          conda install -c conda-forge control=0.10 slycot cvxpy numpy>=2.0 scipy>=1.10.1 -y
          pip install sphinx
      - name: Build | Build with Sphinx
        run: |
          sphinx-build -M html _sphinx docs
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/
  # Deploy job
  deploy:
    needs: build-with-sphinx
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
