name: Deploy Sphinx documentation to GitHub Pages

on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash -el {0}

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    # permissions:
    #   pages: write
    #   id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Make conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.13"
      - name: Install dependencies
        run: |
          conda install -c conda-forge control=0.10 slycot cvxpy numpy>=2.0 scipy>=1.10.1 -y
      - name: Running the Sphinx to gh-pages Action
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v2.1.0
        with:
          branch: main
          dir_docs: _sphinx
