name: Deploy Sphinx documentation to GitHub Pages

on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash -el {0}

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.13'
      - name: Install dependencies
        run: |
          conda install -c conda-forge control=${{ matrix.control-version }} slycot cvxpy numpy>=2.0 scipy>=1.10.1 -y
      - id: deployment
        uses: sphinx-notes/pages@v3
        with:
          python_version: '3.13'
          documentation_path: '_sphinx'
