# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        activate-environment: nqlib-test
        python-version: ${{ matrix.python-version }}
    - name: Install deps
      run: |
        conda activate nqlib-test
        conda install -c conda-forge control slycot cvxpy -y
        conda install numpy scipy -y
    - name: Test with unittest
      run: |
        conda activate nqlib-test
        python -m unittest discover tests
