# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test NQLib

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

defaults:
  run:
    shell: bash -el {0}
jobs:
  test:
    name: Test with Python ${{ matrix.python-version }}, control ${{ matrix.control-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        control-version: ["0.9.4", "0.10"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          conda install -c conda-forge control=${{ matrix.control-version }} slycot cvxpy numpy>=2.0 scipy>=1.10.1 -y
      - name: Test with unittest
        run: |
          pip install --editable .
          python -m pytest --doctest-modules
